/* Populated by react-webpack-redux:action */
export const SET_FILTER = 'SET_FILTER';
export const ADD_SKILL = 'ADD_SKILL';
export const REMOVE_SKILL = 'REMOVE_SKILL';
export const STYLE = 'STYLE';
export const WEAPON_MODDING = 'WEAPON_MODDING';
export const MODDING_MULTI = 'MODDING_MULTI';
export const DEMODDING_MULTI = 'DEMODDING_MULTI';
export const MODDING_CAPACITY = 'MODDING_CAPACITY';
export const DEMODDING_CAPACITY = 'DEMODDING_CAPACITY';
